import Link from "next/link";
import NavBar from "@/components/NavBar";
import { CALCULATOR_GROUPS } from "@/lib/calculatorCatalog";
import { WORKED_EXAMPLES, TOTAL_EXAMPLES } from "@/lib/workedExamples";

export default function ExamplesIndexPage() {
  const groupsWithExamples = CALCULATOR_GROUPS.map((g) => ({
    group: g,
    examples: WORKED_EXAMPLES.filter((e) => e.groupId === g.id),
  })).filter((g) => g.examples.length > 0);

  return (
    <div className="flex flex-1 flex-col">
      <NavBar />

      <div className="mx-auto w-full max-w-6xl px-6 py-10">
        <h1 className="text-2xl font-semibold text-foreground sm:text-3xl">Worked Examples</h1>
        <p className="mt-2 max-w-2xl text-muted">
          Full step-by-step calculations with standard clause references at every stage — {TOTAL_EXAMPLES}{" "}
          examples so far, growing toward at least one per calculator. Every number is generated by the
          calculator&apos;s own verified engine, not hand-typed.
        </p>

        {groupsWithExamples.length === 0 && (
          <p className="mt-10 text-muted">More worked examples are on the way — check back soon.</p>
        )}

        <div className="mt-10 space-y-12">
          {groupsWithExamples.map(({ group, examples }) => (
            <section key={group.id} id={group.id}>
              <h2 className="text-xl font-semibold text-foreground">{group.title}</h2>
              <p className="mt-1 text-sm text-muted">{group.description}</p>
              <div className="mt-4 grid gap-4 sm:grid-cols-2">
                {examples.map((ex) => (
                  <Link
                    key={ex.slug}
                    href={`/examples/${ex.slug}`}
                    className="group flex flex-col rounded-xl border border-border bg-surface p-5 transition-colors hover:border-accent/40"
                  >
                    <div className="flex flex-wrap items-center gap-2">
                      <span className="rounded-full border border-accent/30 bg-accent/10 px-2 py-0.5 text-[11px] font-medium text-accent">
                        {ex.standard}
                      </span>
                      <span className="text-[11px] text-muted">{ex.readTime}</span>
                    </div>
                    <h3 className="mt-2.5 text-sm font-semibold text-foreground">{ex.title}</h3>
                    <p className="mt-1.5 flex-1 text-xs text-muted">{ex.dek}</p>
                    <span className="mt-3 text-xs font-semibold text-accent-2 group-hover:opacity-80">
                      Read the worked example →
                    </span>
                  </Link>
                ))}
              </div>
            </section>
          ))}
        </div>
      </div>
    </div>
  );
}
