import Link from "next/link";
import NavBar from "@/components/NavBar";
import { BookOpen, GraduationCap } from "lucide-react";
import { TOTAL_GUIDES } from "@/lib/guides";
import { TOTAL_EXAMPLES } from "@/lib/workedExamples";
import { CALCULATOR_GROUPS } from "@/lib/calculatorCatalog";

export default function ResourcesHubPage() {
  return (
    <div className="flex flex-1 flex-col">
      <NavBar />

      <div className="mx-auto w-full max-w-5xl px-6 py-10">
        <h1 className="text-2xl font-semibold text-foreground sm:text-3xl">Resources</h1>
        <p className="mt-2 max-w-2xl text-muted">
          Everything on AJapps that teaches rather than calculates — conceptual guides for each
          category, and step-by-step worked examples for individual problems.
        </p>

        <div className="mt-10 grid gap-6 sm:grid-cols-2">
          <Link
            href="/guides"
            className="group flex flex-col rounded-xl border border-border bg-surface p-7 transition-colors hover:border-accent/40"
          >
            <GraduationCap className="h-8 w-8 text-accent-2" aria-hidden="true" />
            <h2 className="mt-4 text-xl font-semibold text-foreground">Guides</h2>
            <p className="mt-2 flex-1 text-sm text-muted">
              Category primers: core engineering concepts, the standards landscape, and a sensible
              order to work through each category&apos;s calculators — {TOTAL_GUIDES} so far, growing
              toward one per category across all {CALCULATOR_GROUPS.length} categories.
            </p>
            <span className="mt-4 text-sm font-semibold text-accent-2 group-hover:opacity-80">
              Browse guides →
            </span>
          </Link>

          <Link
            href="/examples"
            className="group flex flex-col rounded-xl border border-border bg-surface p-7 transition-colors hover:border-accent/40"
          >
            <BookOpen className="h-8 w-8 text-accent-2" aria-hidden="true" />
            <h2 className="mt-4 text-xl font-semibold text-foreground">Worked Examples</h2>
            <p className="mt-2 flex-1 text-sm text-muted">
              Full step-by-step calculations with standard clause references at every stage —{" "}
              {TOTAL_EXAMPLES} examples covering every live calculator. Every number is generated by
              the calculator&apos;s own verified engine, not hand-typed.
            </p>
            <span className="mt-4 text-sm font-semibold text-accent-2 group-hover:opacity-80">
              Browse worked examples →
            </span>
          </Link>
        </div>

        <div className="mt-10 rounded-xl border border-border bg-surface-2 p-6 text-sm text-muted">
          Not sure which to start with? A <span className="font-medium text-foreground">Guide</span>{" "}
          is the right place to start if you&apos;re new to a category and want the underlying theory
          before touching a calculator. A{" "}
          <span className="font-medium text-foreground">Worked Example</span> is the right place to
          start if you already know roughly what you&apos;re doing and want to see one specific
          problem solved end to end.
        </div>
      </div>
    </div>
  );
}
