// Worked examples for the Protection & Relaying group. Every numeric value
// below was generated by running the calculator's own already-verified
// engine (idmt.ts / idmtef.ts / idmtgrading.ts / difftransformer.ts /
// faultpropagation.ts / arcflash.ts / breakerfuse.ts / gensync.ts /
// gensyncfault.ts) with the stated inputs in a standalone Node script, not
// hand-typed — see the project's calculation-verification workflow in
// README.md. Most examples reuse each calculator's own default input set
// (the same values a visitor sees when the page first loads), so the
// worked example and the live calculator can never silently diverge.

import type { WorkedExample } from "./types";

export const PROTECTION_EXAMPLES: WorkedExample[] = [
  {
    slug: "idmt-relay-coordination-two-relay-grading",
    groupId: "protection",
    calculatorHref: "/calculators/idmt",
    calculatorName: "IDMT Relay Coordination",
    title: "Worked Example: IDMT Relay Grading Across a Full Fault-Current Range",
    dek: "Two IEC Standard Inverse relays look correctly graded at one fault current — until the full-range sweep reveals the margin collapses at higher currents.",
    standard: "IEC 60255-151",
    readTime: "9 min read",
    scenario: [
      { label: "Relay 1 (downstream)", value: "Pickup 100 A, CT 1:1, TMS 0.1, IEC Standard Inverse (SI)" },
      { label: "Relay 2 (upstream)", value: "Pickup 150 A, CT 1:1, TMS 0.25, IEC Standard Inverse (SI)" },
      { label: "Test fault current", value: "2000 A" },
      { label: "Full sweep range", value: "105 A – 10,000 A (the calculator's default range)" },
      { label: "Required grading margin (CTI)", value: "0.4 s" },
    ],
    scenarioNote: "Relay 1 protects a feeder; Relay 2 is the upstream backup device one bus further up. Both must trip in the right order with enough time separation, at every current either relay could realistically see.",
    steps: [
      {
        title: "Find each relay's multiple of pickup at the test fault current",
        equationLabel: "Eq. 1",
        equation: "M = Ifault / Ipickup",
        substitution: "M1 = 2000 / 100 = 20 x       M2 = 2000 / 150 = 13.3 x",
        result: "M1 = 20 x, M2 = 13.3 x",
      },
      {
        title: "Apply the IEC Standard Inverse equation to each relay",
        body: "IEC 60255-151 defines the Standard Inverse (SI) curve with k = 0.14 and alpha = 0.02.",
        equationLabel: "Eq. 2",
        equation: "t = TMS x (k / (M^alpha - 1))",
        substitution: "t1 = 0.1 x (0.14 / (20^0.02 - 1)) = 0.227 s\nt2 = 0.25 x (0.14 / (13.3^0.02 - 1)) = 0.658 s",
        result: "t1 = 0.227 s, t2 = 0.658 s",
      },
      {
        title: "Check the margin at this one test point",
        equation: "margin = t2 - t1",
        substitution: "margin = 0.658 - 0.227",
        result: "margin = 0.432 s -> passes the 0.4 s requirement",
        note: "This is the check most hand calculations stop at. It looks fine.",
      },
      {
        title: "Sweep the full fault-current range instead of one point",
        body: "Real faults land anywhere in the range a relay can see, not just at one convenient test current. Recomputing the margin at every point across 105 A-10,000 A finds where it is smallest.",
        table: {
          headers: ["Fault current", "t1 (Relay 1)", "t2 (Relay 2)", "Margin"],
          rows: [
            ["2000 A", "0.227 s", "0.658 s", "0.432 s"],
            ["10,000 A (worst case)", "0.145 s", "0.399 s", "0.254 s"],
          ],
        },
        result: "Worst-case margin = 0.254 s at 10,000 A",
        note: "IEC inverse curves flatten out at high multiples of pickup, which is why the two relays' trip times converge — and the margin shrinks — as fault current rises.",
      },
    ],
    resultSummary: [
      { check: "Margin at the single 2000 A test point", requirement: "≥ 0.4 s", actual: "0.432 s", pass: true },
      { check: "Worst-case margin, full 105 A–10,000 A sweep", requirement: "≥ 0.4 s", actual: "0.254 s at 10,000 A", pass: false },
    ],
    finalAnswer: "As configured, this relay pair passes the single-point check at 2000 A but FAILS the full-range sweep — the settings are not acceptable as-is and need adjustment before commissioning.",
    keyInsight: "A comfortable margin at one arbitrarily chosen fault current does not guarantee coordination everywhere. IEC inverse curves compress at high current multiples, so the worst-case point is often at the top of the range, not the bottom — which is exactly why this calculator sweeps the whole range by default instead of checking a single current.",
    faqs: [
      {
        q: "What setting change fixes the margin?",
        a: "Raising Relay 2's time multiplier setting (TMS) from 0.25 to roughly 0.34 restores at least 0.4 s of margin across the entire 105 A–10,000 A range, without affecting Relay 1's own trip times.",
      },
      {
        q: "Why does the margin shrink at higher fault current for IEC curves?",
        a: "The IEC inverse-time equation t = TMS x (k / (M^alpha - 1)) approaches TMS x k / M^alpha as M grows, so at high multiples of pickup the trip time is dominated by the curve's shape rather than the TMS offset — two relays on the same curve family converge toward each other's trip times as current rises.",
      },
      {
        q: "Is 0.4 s always the right grading margin?",
        a: "0.4 s (400 ms) is a commonly used CTI (coordination time interval) for electromechanical relays, covering breaker interrupting time, relay overtravel and a safety margin. Modern numerical relays with no overtravel are sometimes graded to 0.2-0.3 s — always confirm against your utility's or plant's own protection philosophy document.",
      },
    ],
  },

  {
    slug: "idmt-earth-fault-relay-50n-51n",
    groupId: "protection",
    calculatorHref: "/calculators/idmt-earth-fault",
    calculatorName: "IDMT Earth Fault Relay (50N/51N)",
    title: "Worked Example: Earth Fault Relay Trip Time with a Dual-Stage (50N/51N) Scheme",
    dek: "An earth-fault relay with both an inverse-time (51N) stage and a high-set instantaneous (50N) stage, checked at two different fault levels.",
    standard: "IEC 60255-151",
    readTime: "8 min read",
    scenario: [
      { label: "Relay pickup (Ie>)", value: "0.2 A (relay/secondary side)" },
      { label: "CT ratio", value: "200 : 1" },
      { label: "Time multiplier (TMS)", value: "0.2, IEC Standard Inverse (SI)" },
      { label: "Instantaneous stage (Ie>>)", value: "4000 A primary, 0.05 s definite-time delay" },
      { label: "Case A — primary earth fault current", value: "1500 A" },
      { label: "Case B — primary earth fault current", value: "5000 A" },
    ],
    steps: [
      {
        title: "Refer the primary fault current to the relay side via the CT ratio",
        equation: "Ie = Ifault(primary) / CT ratio",
        substitution: "Case A: Ie = 1500 / 200 = 7.5 A       Case B: Ie = 5000 / 200 = 25 A",
        result: "Case A: 7.5 A, Case B: 25 A",
      },
      {
        title: "Compute the plug setting multiplier (PSM)",
        equation: "PSM = Ie / pickup",
        substitution: "Case A: PSM = 7.5 / 0.2 = 37.5       Case B: PSM = 25 / 0.2 = 125",
        result: "Case A: PSM = 37.5, Case B: PSM = 125",
      },
      {
        title: "Apply the IEC SI curve for the inverse-time (51N) stage",
        equation: "t = TMS x (0.14 / (PSM^0.02 - 1))",
        substitution: "Case A: t = 0.2 x (0.14 / (37.5^0.02 - 1)) = 0.372 s\nCase B: t = 0.2 x (0.14 / (125^0.02 - 1)) = 0.276 s",
        result: "Case A: 0.372 s, Case B: 0.276 s",
      },
      {
        title: "Check whether the fault exceeds the instantaneous (50N) pickup",
        body: "The high-set instantaneous stage bypasses the inverse-time curve entirely for severe faults, tripping on a short fixed delay instead.",
        table: {
          headers: ["Case", "Primary fault current", "50N pickup", "Instantaneous stage"],
          rows: [
            ["A", "1500 A", "4000 A", "Restrained — below pickup"],
            ["B", "5000 A", "4000 A", "Operates in 0.05 s (definite time)"],
          ],
        },
      },
    ],
    resultSummary: [
      { check: "Case A (1500 A) — governing trip path", requirement: "n/a", actual: "51N inverse-time stage, 0.372 s", pass: true },
      { check: "Case B (5000 A) — governing trip path", requirement: "n/a", actual: "50N instantaneous stage, 0.05 s (bypasses the 0.276 s IDMT time)", pass: true },
    ],
    finalAnswer: "At 1500 A the relay clears the fault on its inverse-time curve in 0.372 s. At 5000 A the instantaneous stage takes over and clears it in 0.05 s — roughly 5x faster — because the fault now exceeds the 4000 A high-set pickup.",
    keyInsight: "A dual-stage scheme gives you both worlds: the inverse-time stage keeps grading margin with downstream/upstream devices for moderate faults, while the instantaneous stage clears severe, close-in faults almost immediately, since there's no coordination need at currents that high — nothing downstream should still be carrying that much fault current.",
    faqs: [
      {
        q: "Why not just set the instantaneous stage very low and skip the inverse-time curve entirely?",
        a: "An instantaneous stage set too low would trip for faults further down the network that a downstream device should clear first, defeating coordination. The high-set pickup is deliberately set above any fault level the relay should see from a downstream fault, so it only operates for faults close to the relay itself.",
      },
      {
        q: "What does PSM mean physically?",
        a: "The plug setting multiplier is simply how many times over pickup the relay is currently seeing. A PSM of 1.0 is right at the trip threshold (technically never trips, since the curve is asymptotic there); higher PSM means a more severe fault and a faster trip time.",
      },
    ],
  },

  {
    slug: "multi-bus-idmt-relay-grading-chain",
    groupId: "protection",
    calculatorHref: "/calculators/idmt-grading",
    calculatorName: "Multi-Bus IDMT Grading",
    title: "Worked Example: Grading a Three-Relay IDMT Chain at a Single Fault Current",
    dek: "A load-end, mid-feeder and source relay all see the same fault — checking whether each step up the chain has enough time separation from the one below it.",
    standard: "IEC 60255-151",
    readTime: "9 min read",
    scenario: [
      { label: "Relay 1 (load end)", value: "Pickup 1 A, CT 200:1, TMS 0.1, IEC SI" },
      { label: "Relay 2 (mid-feeder)", value: "Pickup 1.2 A, CT 300:1, TMS 0.2, IEC SI" },
      { label: "Relay 3 (source)", value: "Pickup 1.5 A, CT 400:1, TMS 0.3, IEC SI" },
      { label: "Fault current (seen by all three)", value: "5000 A primary" },
      { label: "Required grading margin", value: "0.4 s at every step" },
    ],
    steps: [
      {
        title: "Compute each relay's plug setting multiplier at 5000 A",
        equation: "PSM = (Ifault / CT ratio) / pickup",
        substitution: "Relay 1: (5000/200)/1 = 25       Relay 2: (5000/300)/1.2 = 13.9       Relay 3: (5000/400)/1.5 = 8.3",
        result: "PSM1 = 25, PSM2 = 13.9, PSM3 = 8.3",
      },
      {
        title: "Apply the IEC SI curve with each relay's own TMS",
        equation: "t = TMS x (0.14 / (PSM^0.02 - 1))",
        substitution: "t1 = 0.211 s (TMS 0.1)\nt2 = 0.518 s (TMS 0.2)\nt3 = 0.970 s (TMS 0.3)",
        result: "t1 = 0.211 s, t2 = 0.518 s, t3 = 0.970 s",
      },
      {
        title: "Check the grading margin at each step of the chain",
        table: {
          headers: ["Step", "Downstream time", "Upstream time", "Margin", "Requirement"],
          rows: [
            ["Relay 1 → Relay 2", "0.211 s", "0.518 s", "0.308 s", "0.4 s — FAIL"],
            ["Relay 2 → Relay 3", "0.518 s", "0.970 s", "0.451 s", "0.4 s — PASS"],
          ],
        },
      },
    ],
    resultSummary: [
      { check: "Relay 1 → Relay 2 margin", requirement: "≥ 0.4 s", actual: "0.308 s", pass: false },
      { check: "Relay 2 → Relay 3 margin", requirement: "≥ 0.4 s", actual: "0.451 s", pass: true },
    ],
    finalAnswer: "The chain fails overall: Relay 2's TMS of 0.2 is too close to Relay 1's 0.1 to hold a 0.4 s margin at 5000 A, even though the next step up (Relay 2 to Relay 3) passes comfortably.",
    keyInsight: "A grading chain is only as strong as its weakest step — one under-margined pair anywhere in the chain fails the whole study, regardless of how much margin exists elsewhere. Raising Relay 2's TMS to about 0.24 restores the required 0.4 s at this fault level without touching Relay 1 or Relay 3.",
    faqs: [
      {
        q: "Does fixing Relay 2's TMS affect the Relay 2 → Relay 3 step?",
        a: "Yes — raising Relay 2's TMS increases its own trip time everywhere, which widens the Relay 1 → Relay 2 margin but narrows the Relay 2 → Relay 3 margin. In this case there's enough headroom (0.451 s against a 0.4 s requirement) to absorb the small increase, but it should always be rechecked, not assumed.",
      },
      {
        q: "Should this be checked at more than one fault current?",
        a: "Yes — a production grading study checks the full range of currents each relay could see (minimum fault at the far end of the protected zone through to maximum fault close to the source), not just one value, for the same reason the two-relay coordination example on this site shows a single-point check can hide a full-range failure.",
      },
    ],
  },

  {
    slug: "transformer-differential-protection-87t",
    groupId: "protection",
    calculatorHref: "/calculators/transformer-differential",
    calculatorName: "Transformer Differential Protection (87T)",
    title: "Worked Example: Percentage-Bias Differential Protection — Restraint vs. Trip",
    dek: "The same dual-slope 87T characteristic correctly restrains through normal load with CT mismatch, then trips decisively for a genuine internal fault.",
    standard: "IEEE C37.91 (guide-consistent)",
    readTime: "10 min read",
    scenario: [
      { label: "Minimum pickup (Id0)", value: "0.3 p.u." },
      { label: "First slope", value: "25%, up to a restraint current of 2.0 p.u." },
      { label: "Second slope", value: "60%, above 2.0 p.u. restraint" },
      { label: "Case A — normal load", value: "I1 = 1.05 p.u. in, I2 = 0.98 p.u. out (typical CT ratio-error mismatch)" },
      { label: "Case B — internal fault", value: "I1 = 6.0 p.u. in, I2 = 0.5 p.u. out (winding short collapses the outflow)" },
    ],
    scenarioNote: "Currents are already referred to a common base (CT secondary, ratio and vector-group compensated) as the relay itself would see them.",
    steps: [
      {
        title: "Compute differential and restraint (bias) current for each case",
        equation: "Id = |I1 - I2|          Ir = (I1 + I2) / 2",
        substitution: "Case A: Id = |1.05 - 0.98| = 0.07 p.u.   Ir = (1.05+0.98)/2 = 1.015 p.u.\nCase B: Id = |6.0 - 0.5| = 5.5 p.u.   Ir = (6.0+0.5)/2 = 3.25 p.u.",
        result: "Case A: Id = 0.07 p.u., Ir = 1.015 p.u.   Case B: Id = 5.5 p.u., Ir = 3.25 p.u.",
      },
      {
        title: "Find the operate threshold at each restraint current",
        body: "Case A's restraint (1.015 p.u.) is below the 2.0 p.u. knee, so only the first slope applies. Case B's restraint (3.25 p.u.) is above the knee, so the threshold is the value at the knee plus the second, steeper slope beyond it.",
        equation: "Below knee: threshold = Id0 + slope1 x Ir\nAbove knee: threshold = (Id0 + slope1 x knee) + slope2 x (Ir - knee)",
        substitution: "Case A: 0.3 + 0.25 x 1.015 = 0.554 p.u.\nCase B: (0.3 + 0.25 x 2.0) + 0.60 x (3.25 - 2.0) = 0.8 + 0.75 = 1.55 p.u.",
        result: "Case A threshold = 0.554 p.u.   Case B threshold = 1.55 p.u.",
      },
      {
        title: "Compare differential current to the threshold",
        table: {
          headers: ["Case", "Id", "Threshold", "Verdict"],
          rows: [
            ["A — normal load, CT mismatch", "0.07 p.u.", "0.554 p.u.", "Restrained — no trip (correct)"],
            ["B — internal fault", "5.5 p.u.", "1.55 p.u.", "Trips (correct)"],
          ],
        },
      },
    ],
    resultSummary: [
      { check: "Case A — stays restrained through normal load", requirement: "Id < threshold", actual: "0.07 p.u. < 0.554 p.u.", pass: true },
      { check: "Case B — trips for a genuine internal fault", requirement: "Id ≥ threshold", actual: "5.5 p.u. ≥ 1.55 p.u.", pass: true },
    ],
    finalAnswer: "The dual-slope characteristic does its job in both directions: it stays securely restrained through the everyday CT ratio-error of normal load (Case A), and trips decisively and quickly for a real internal winding fault (Case B).",
    keyInsight: "A flat, fixed-pickup differential element would have to be set high enough to ride through worst-case CT mismatch at maximum through-load — which would make it dangerously insensitive to genuine internal faults. The percentage-bias characteristic solves this by letting the pickup threshold rise with restraint current, staying tight (sensitive) at low load and only relaxing (for security against CT saturation) at high through-fault currents.",
    faqs: [
      {
        q: "Why does the threshold rise instead of staying at a fixed pickup?",
        a: "Real CTs have small ratio errors that scale with the current flowing through them, and those errors get worse (relative CT saturation) during high through-fault current. If the pickup stayed fixed at a low value, a large external fault could saturate the CTs enough to look like a differential current and cause a false trip. The second, steeper slope specifically defends against that scenario.",
      },
      {
        q: "What's a typical range for the two slope settings?",
        a: "First slopes of 20-30% and second slopes of 50-80% above a knee around 2-8 p.u. restraint current are common starting points, but the right values depend on the specific CTs, their accuracy class and knee-point voltage, and the transformer's tap-changer range — always confirm against manufacturer guidance and a proper CT saturation study for a real installation.",
      },
    ],
  },

  {
    slug: "fault-current-propagation-base-kva-method",
    groupId: "protection",
    calculatorHref: "/calculators/fault-propagation",
    calculatorName: "Fault Current Propagation (Base kVA Method)",
    title: "Worked Example: Available Fault Current from Utility Source Down to a Sub-Panel",
    dek: "Using the classic Base kVA Method to estimate available short-circuit current at two points down a radial LV network, and checking a downstream breaker's interrupting rating against it.",
    standard: "Base kVA Method (textbook per-unit impedance)",
    readTime: "9 min read",
    scenario: [
      { label: "Base", value: "1000 kVA" },
      { label: "System voltage", value: "415 V line-to-line" },
      { label: "Utility source fault level", value: "250 MVA" },
      { label: "Transformer", value: "1000 kVA, 6% impedance (own base)" },
      { label: "Cable, transformer to sub-panel", value: "1.5% impedance (on the 1000 kVA base)" },
      { label: "Sub-panel main breaker", value: "Example: rated 22 kA interrupting capacity" },
    ],
    steps: [
      {
        title: "Convert the utility source fault level to %Z on the chosen base",
        equation: "%Z(source) = (baseMVA / sourceFaultMVA) x 100",
        substitution: "%Z(source) = (1 / 250) x 100 = 0.4%",
        result: "Source impedance = 0.4% on the 1000 kVA base",
      },
      {
        title: "Add the transformer impedance (already on the same base) and find the fault at its secondary",
        equation: "Cumulative %Z = 0.4% + 6% = 6.4%",
        substitution: "Fault MVA = (baseMVA x 100) / cumulative %Z = (1 x 100) / 6.4 = 15.625 MVA\nIfault = Fault MVA / (√3 x kV) = 15.625 / (1.732 x 0.415)",
        result: "Fault current at transformer secondary = 21.7 kA",
      },
      {
        title: "Add the cable impedance and find the fault at the sub-panel",
        equation: "Cumulative %Z = 6.4% + 1.5% = 7.9%",
        substitution: "Fault MVA = 100 / 7.9 = 12.66 MVA\nIfault = 12.66 / (1.732 x 0.415)",
        result: "Fault current at sub-panel = 17.6 kA",
      },
      {
        title: "Check the sub-panel breaker's interrupting rating against the worst-case fault it must clear",
        equation: "Rated interrupting capacity ≥ available fault current",
        substitution: "22 kA ≥ 17.6 kA",
        result: "Passes, with roughly 25% margin",
      },
    ],
    resultSummary: [
      { check: "Fault current at transformer secondary bus", requirement: "n/a (informational)", actual: "21.7 kA", pass: true },
      { check: "Fault current at sub-panel", requirement: "n/a (informational)", actual: "17.6 kA", pass: true },
      { check: "Sub-panel breaker interrupting rating", requirement: "≥ 17.6 kA", actual: "22 kA rated", pass: true },
    ],
    finalAnswer: "Available fault current drops from 21.7 kA at the transformer secondary to 17.6 kA at the sub-panel as cable impedance is added, and the example 22 kA breaker comfortably clears the worse of the two.",
    keyInsight: "This method sums %Z values arithmetically (scalar addition) rather than resolving each element into resistance and reactance and combining them vectorially. That's the classic quick-estimate version of the method — it slightly overstates total impedance and therefore understates fault current relative to a full R+jX study, so it should never be used to finalize a protective device's interrupting rating on its own; treat the result as a first screening figure, then verify with a full short-circuit study before specifying equipment.",
    faqs: [
      {
        q: "Why does fault current go down as you move away from the source?",
        a: "Every element between the source and a given point — the transformer, cables, busbars — adds its own impedance to the total fault-current path. More cumulative impedance means less current can flow for a given system voltage, so available fault current is always highest right at (or upstream of) the source and decreases at each downstream point.",
      },
      {
        q: "Why convert everything to the same kVA base?",
        a: "Percentage or per-unit impedance values are only meaningful relative to a stated power base — a transformer's 6% impedance is 6% of its own rated kVA. To add impedances from different equipment together, they must first be converted onto one common base, which is exactly what the elementBaseKva field on each element does before summing.",
      },
    ],
  },

  {
    slug: "arc-flash-incident-energy-lv-mcc",
    groupId: "protection",
    calculatorHref: "/calculators/arc-flash",
    calculatorName: "Arc Flash",
    title: "Worked Example: Arc Flash Incident Energy and PPE Category for a 415 V MCC",
    dek: "A routine incident-energy calculation for a low-voltage motor control centre — and why a result that's barely above one PPE threshold still requires the next full category up.",
    standard: "IEEE 1584-2002",
    readTime: "11 min read",
    scenario: [
      { label: "Bolted fault current (Ibf)", value: "25 kA" },
      { label: "System voltage", value: "415 V (0.415 kV)" },
      { label: "Equipment class", value: "LV MCC / Panelboard — gap 25 mm, exponent x = 1.641" },
      { label: "Enclosure", value: "Box (typical switchgear/MCC enclosure)" },
      { label: "System grounding", value: "Grounded" },
      { label: "Working distance", value: "455 mm" },
      { label: "Protective device clearing time", value: "0.2 s" },
    ],
    steps: [
      {
        title: "Compute arcing current (IEEE 1584-2002 Eq. 2a, valid 0.208–1 kV)",
        equation: "lg(Ia) = K + 0.662 lg(Ibf) + 0.0966V + 0.000526G + 0.5588V lg(Ibf) - 0.00304G lg(Ibf)",
        substitution: "K = -0.097 (box enclosure); solving with Ibf = 25 kA, V = 0.415 kV, G = 25 mm",
        result: "Ia = 12.58 kA (about 50% of bolted fault current)",
      },
      {
        title: "Compute normalized incident energy at the standard 610 mm / 0.2 s reference",
        equation: "lg(En) = K1 + K2 + 1.081 lg(Ia) + 0.0011G",
        substitution: "K1 = -0.555 (box), K2 = -0.113 (grounded)",
        result: "En = 3.53 (normalized incident energy)",
      },
      {
        title: "Scale to the actual working distance and clearing time",
        equation: "E = Cf x En x (t / 0.2) x (610^x / D^x)",
        substitution: "Cf = 1.5 (≤1 kV); t = 0.2 s; D = 455 mm; x = 1.641",
        result: "E = 8.57 cal/cm²",
      },
      {
        title: "Compute the arc flash boundary (distance at which E = 1.2 cal/cm²)",
        equation: "AFB = [Cf x En x (t/0.2) x 610^x / 1.2]^(1/x)",
        result: "AFB ≈ 1508 mm (about 1.5 m)",
      },
      {
        title: "Select the PPE category",
        body: "Category bands are defined by arc rating ceilings: Cat 1 up to 4 cal/cm², Cat 2 up to 8, Cat 3 up to 25, Cat 4 up to 40.",
        result: "8.57 cal/cm² falls just above the Category 2 ceiling — Category 3 PPE required",
      },
    ],
    resultSummary: [
      { check: "Incident energy at 455 mm working distance", requirement: "n/a (informational)", actual: "8.57 cal/cm²", pass: true },
      { check: "Arc flash boundary", requirement: "n/a (informational)", actual: "≈1.51 m", pass: true },
      { check: "PPE category selection", requirement: "Match E to the correct band", actual: "Category 3 (≥25 cal/cm² rated PPE)", pass: true },
    ],
    finalAnswer: "At this MCC's normal working distance, incident energy comes out to 8.57 cal/cm² — only 0.57 cal/cm² over the Category 2 ceiling, but that's still enough to require the full jump to Category 3 PPE (rated ≥25 cal/cm²) and a 1.51 m arc flash boundary.",
    keyInsight: "PPE categories are step functions, not a continuous scale — a result that's barely over a threshold requires the same PPE as a result far over it. That's a strong argument for treating a calculated incident energy close to a boundary with extra caution (e.g. re-verify input assumptions like clearing time) rather than assuming you're 'basically' in the lower category.",
    faqs: [
      {
        q: "Why is arcing current only about half the bolted fault current?",
        a: "An arc has its own impedance (the arc itself resists current flow, unlike a true bolted short), so arcing current is always somewhat lower than the bolted (zero-impedance) fault current used as the calculation's starting point — IEEE 1584's empirical equations capture this relationship from tested arc data rather than assuming a fixed ratio.",
      },
      {
        q: "What's the single biggest lever for reducing incident energy here?",
        a: "Clearing time (t) enters the incident-energy equation linearly, so it has an outsized effect — a protective device that trips in 0.1 s instead of 0.2 s roughly halves the incident energy for the same fault. Faster, well-coordinated protection (or a maintenance-mode setting that temporarily lowers pickup/delay while someone is working on the equipment) is usually more effective than trying to change working distance or system voltage.",
      },
      {
        q: "Does this apply above 1 kV?",
        a: "No — this example uses IEEE 1584-2002's Eq. 2a, valid only for 0.208-1 kV systems. Systems from 1-15 kV use the standard's separate Eq. 2b, which has no voltage, gap or enclosure dependency; using the wrong equation for the voltage range produces badly overstated (nonphysical) results, which is exactly the bug this calculator's own methodology note documents finding and fixing.",
      },
    ],
  },

  {
    slug: "circuit-breaker-fuse-sizing-nec",
    groupId: "protection",
    calculatorHref: "/calculators/breaker-fuse-sizer",
    calculatorName: "Circuit Breaker & Fuse Sizer",
    title: "Worked Example: OCPD Sizing for a General Load and a Motor Circuit per NEC",
    dek: "Two different sizing rules in the same calculator — a general continuous/non-continuous load, and a motor branch circuit sized for starting-current withstand instead of running current.",
    standard: "NEC 210.19/215.2 + 240.4, NEC 430.52",
    readTime: "10 min read",
    scenario: [
      { label: "General load — continuous", value: "80 A" },
      { label: "General load — non-continuous", value: "20 A" },
      { label: "Cable ampacity (Iz)", value: "130 A" },
      { label: "Motor full-load current (FLC)", value: "34 A" },
      { label: "Motor category", value: "\"Other\" (NEC Table 430.52(C)(1))" },
      { label: "OCPD type (motor path)", value: "Time-delay fuse" },
    ],
    steps: [
      {
        title: "General load — compute the minimum OCPD rating",
        body: "NEC 210.19(A)(1)/215.2(A)(1) require 125% of continuous load plus 100% of non-continuous load.",
        equation: "minOCPD = 1.25 x Icontinuous + 1.0 x Inon-continuous",
        substitution: "minOCPD = 1.25 x 80 + 1.0 x 20 = 100 + 20",
        result: "minOCPD = 120 A",
      },
      {
        title: "Round up to the next standard NEC 240.6(A) size",
        result: "Recommended OCPD = 125 A",
      },
      {
        title: "Verify the cable is protected (NEC 240.4)",
        equation: "Recommended OCPD ≤ cable ampacity Iz?",
        substitution: "125 A ≤ 130 A",
        result: "Yes — cable is directly protected, no exception needed",
      },
      {
        title: "Motor circuit — compute the OCPD from FLC, not running current",
        body: "NEC 430.52(C)(1) sizes the branch-circuit OCPD as a percentage of motor full-load current to survive inrush/starting current, not steady-state running current. \"Other\" motors on a time-delay fuse use 175%.",
        equation: "minOCPD = 175% x FLC",
        substitution: "minOCPD = 1.75 x 34 = 59.5 A",
        result: "minOCPD = 59.5 A -> rounds up to 60 A",
      },
      {
        title: "Find the 430.52(C)(1)(b) exception ceiling, in case 60 A can't start the motor",
        body: "If the standard 175% size genuinely can't carry the motor's starting current without nuisance tripping, the exception permits going up to 225% for a time-delay fuse — but only as high as needed, and rounded down to the nearest standard size.",
        equation: "exceptionCeiling = 225% x FLC, rounded down to standard size",
        substitution: "225% x 34 = 76.5 A -> rounds down to 70 A",
        result: "Exception ceiling = 70 A",
      },
    ],
    resultSummary: [
      { check: "General load OCPD protects the cable", requirement: "OCPD ≤ Iz", actual: "125 A ≤ 130 A", pass: true },
      { check: "Motor branch OCPD within NEC 430.52 window", requirement: "60 A – 70 A (standard to exception ceiling)", actual: "60 A recommended", pass: true },
    ],
    finalAnswer: "The general load circuit is protected at 125 A. The motor branch circuit's standard OCPD is 60 A (175% of FLC), with headroom up to 70 A available under the 430.52(C)(1)(b) exception if the motor's starting current trips a 60 A time-delay fuse.",
    keyInsight: "Motor branch-circuit protection is deliberately sized off starting-current withstand (via a percentage of FLC), not the general continuous-load rule — a motor's running current is far below its OCPD rating by design, because the device has to ride through several seconds of inrush at 5-8x FLC without tripping.",
    faqs: [
      {
        q: "Why is the motor OCPD (60 A) so much higher than its running current (34 A) but the general load OCPD is much closer to its load?",
        a: "A motor's OCPD has to survive its own starting current — typically several times FLC for a few seconds during across-the-line starting — without tripping, which is why NEC 430.52 permits sizing it well above running current. A general load's OCPD only has to cover normal continuous operation with a duty-cycle margin, so it stays much closer to actual load.",
      },
      {
        q: "What happens if the cable ampacity is below the recommended OCPD?",
        a: "NEC 240.4(B) allows using the next higher standard OCPD size than the cable's ampacity in specific circumstances (generally up to 800 A, and only where the ampacity doesn't itself correspond to a standard size) — but if that exception doesn't apply, the cable must be upsized instead of oversizing the protective device beyond what the conductor can safely carry.",
      },
    ],
  },

  {
    slug: "generator-sync-check-paralleling",
    groupId: "protection",
    calculatorHref: "/calculators/generator-sync",
    calculatorName: "Generator Sync Check",
    title: "Worked Example: Voltage, Frequency and Phase Checks Before Closing a Generator Breaker",
    dek: "The three checks a synchroscope or sync-check relay makes before it's safe to parallel an incoming generator with a live bus.",
    standard: "General synchronizing practice (ANSI device 25 concept)",
    readTime: "8 min read",
    scenario: [
      { label: "Generator voltage", value: "415 V" },
      { label: "Bus voltage", value: "412 V" },
      { label: "Generator frequency", value: "50.05 Hz" },
      { label: "Bus frequency", value: "50.00 Hz" },
      { label: "Phase angle difference", value: "3°" },
      { label: "Acceptance windows", value: "Voltage ≤5%, frequency ≤0.2 Hz, phase ≤10°" },
    ],
    steps: [
      {
        title: "Compute the voltage difference",
        equation: "voltageDiff% = |Vgen - Vbus| / Vbus x 100",
        substitution: "|415 - 412| / 412 x 100",
        result: "0.73%",
      },
      {
        title: "Compute the frequency difference and the resulting beat period",
        body: "The beat period is the time between successive instants where the two sources are exactly in phase — how long an operator watching a synchroscope has between each pass through the 12 o'clock position.",
        equation: "freqDiff = |fgen - fbus|          beatPeriod = 1 / freqDiff",
        substitution: "freqDiff = |50.05 - 50.00| = 0.05 Hz          beatPeriod = 1 / 0.05",
        result: "freqDiff = 0.05 Hz, beat period = 20 s",
      },
      {
        title: "Check the phase angle reading",
        result: "3° — well within the acceptance window",
      },
      {
        title: "Compare all three against their acceptance windows",
        table: {
          headers: ["Check", "Value", "Window", "Result"],
          rows: [
            ["Voltage difference", "0.73%", "≤5%", "OK"],
            ["Frequency difference", "0.05 Hz", "≤0.2 Hz", "OK"],
            ["Phase angle", "3°", "≤10°", "OK"],
          ],
        },
      },
    ],
    resultSummary: [
      { check: "Voltage difference", requirement: "≤ 5%", actual: "0.73%", pass: true },
      { check: "Frequency difference", requirement: "≤ 0.2 Hz", actual: "0.05 Hz", pass: true },
      { check: "Phase angle difference", requirement: "≤ 10°", actual: "3°", pass: true },
    ],
    finalAnswer: "All three checks pass — it is safe to close the generator breaker and parallel with the bus at this instant.",
    keyInsight: "The beat period (20 s here) is what actually makes manual synchronizing practical: with the generator running only slightly faster than the bus, the phase relationship drifts slowly and predictably, giving an operator a wide, repeating window to close the breaker right as the phase angle crosses zero — rather than a split-second opportunity.",
    faqs: [
      {
        q: "Why must the generator run slightly faster than the bus, not exactly matched?",
        a: "Running marginally faster (a small positive frequency difference) makes the phase angle drift slowly forward and predictably cross zero, giving the operator or sync-check relay a clean, repeating closing window. If the generator ran slightly slower, the phase would drift backward relative to the bus, which is functionally the same principle but conventionally generators are brought up to speed from below and allowed to drift forward.",
      },
      {
        q: "What happens if the breaker closes out of synchronism?",
        a: "Closing significantly out of phase, frequency or voltage causes a large transient current and torque shock to the generator and its prime mover — potentially damaging the windings, shaft or coupling, and in severe cases causing a violent mechanical event. This is exactly why sync-check relays (ANSI device 25) exist to block breaker closure automatically outside the acceptance windows, as a backup to manual synchronizing.",
      },
    ],
  },

  {
    slug: "parallel-generator-fault-contribution",
    groupId: "protection",
    calculatorHref: "/calculators/generator-fault-contribution",
    calculatorName: "Parallel Generator Fault Contribution",
    title: "Worked Example: Fault Current Contribution from Two Paralleled Generators",
    dek: "Two identical 500 kVA gensets running in parallel — how much fault current does each one contribute to a common bus fault, and what does that mean for switchgear rating?",
    standard: "Subtransient-reactance method",
    readTime: "8 min read",
    scenario: [
      { label: "System voltage", value: "415 V line-to-line" },
      { label: "Genset 1", value: "500 kVA, Xd'' = 0.12 p.u." },
      { label: "Genset 2", value: "500 kVA, Xd'' = 0.12 p.u." },
      { label: "Example bus fault rating", value: "15 kA (for comparison)" },
    ],
    steps: [
      {
        title: "Compute each generator's rated current",
        equation: "Irated = (S x 1000) / (√3 x V x 1000)",
        substitution: "Irated = 500,000 / (1.732 x 415)",
        result: "Irated = 695.6 A per generator",
      },
      {
        title: "Compute each generator's subtransient fault contribution",
        body: "The subtransient reactance Xd'' represents the generator's lowest impedance immediately after a fault occurs — the highest current it will momentarily deliver.",
        equation: "Ifault = Irated / Xd''",
        substitution: "Ifault = 695.6 / 0.12",
        result: "Ifault = 5797 A = 5.80 kA per generator",
      },
      {
        title: "Sum both generators' contributions at the common bus",
        body: "This first-approximation method adds each machine's own-base contribution arithmetically, ignoring the (usually small) impedance of the bus and cabling between the two machines.",
        equation: "Itotal = Ifault(1) + Ifault(2)",
        substitution: "Itotal = 5.80 + 5.80",
        result: "Itotal = 11.59 kA",
      },
      {
        title: "Check the total against the bus/switchgear fault rating",
        equation: "Rated interrupting capacity ≥ total fault contribution",
        substitution: "15 kA ≥ 11.59 kA",
        result: "Passes, with about 29% margin",
      },
    ],
    resultSummary: [
      { check: "Fault contribution per generator", requirement: "n/a (informational)", actual: "5.80 kA each", pass: true },
      { check: "Total fault current at common bus", requirement: "n/a (informational)", actual: "11.59 kA", pass: true },
      { check: "Switchgear interrupting rating", requirement: "≥ 11.59 kA", actual: "15 kA rated (example)", pass: true },
    ],
    finalAnswer: "Each generator contributes 5.80 kA to a bus fault; combined, the two units deliver 11.59 kA, which the example 15 kA-rated switchgear clears with about 29% margin.",
    keyInsight: "Fault contribution scales with the number of paralleled machines, not just total installed capacity in isolation — adding a third identical generator would push total fault current toward 17.4 kA, which is exactly the kind of check that needs revisiting every time generation capacity is added to a paralleled bus, since existing switchgear may not have been rated for the new total.",
    faqs: [
      {
        q: "Why use subtransient reactance instead of the generator's steady-state (synchronous) reactance?",
        a: "Immediately after a fault, a generator's effective internal impedance is at its lowest (the subtransient value, Xd''), producing the highest instantaneous fault current — this is the value protective devices and switchgear must be rated to interrupt, even though the current decays toward a lower steady-state value over subsequent cycles as the transient and subtransient effects decay.",
      },
      {
        q: "Does ignoring inter-machine impedance matter?",
        a: "It's a simplifying assumption that's usually conservative for switchgear rating purposes (real bus/cable impedance between machines would slightly reduce the combined fault current), but it does not account for network impedance beyond the immediate bus, so it isn't a substitute for a full short-circuit study when sizing protection for a larger, more complex paralleled system.",
      },
    ],
  },
];
